/* ==========================================================================
   The prospect list.

   Transcribed from `Website.xlsx` in the repository root: one column of
   business names, 25 unique entries across three trades. The spreadsheet's
   other columns (Website made / Called / Interested / Demo shown / Secured)
   are tracking columns for outreach and are deliberately not reproduced here.

   Notes on what is real and what is not:
     - `name` is the business name from the spreadsheet (lightly tidied —
       all-caps names and trailing operator names are normalised for display,
       with the original kept in `listedAs`).
     - The spreadsheet has no addresses, so the contact details on every demo
       are obvious placeholders: a 0000 0000 phone number, example.com email,
       and a generic service area unless the business name itself names one.
     - Everything else — menus, prices, hours, reviews, photos — is invented
       sample content, exactly like the four style demos.
   ========================================================================== */

/** Accent colour and page tint per theme. Keys are used as `data-theme`. */
export const THEMES = {
  bistro: { accent: "#9a4a3c", bg: "#faf4e9" },
  cafe: { accent: "#6c8451", bg: "#fbf8ee" },
  trade: { accent: "#2f5d80", bg: "#f7f5f0" },
  grocery: { accent: "#5b7f3f", bg: "#faf8ee" },

  wok: { accent: "#b0432b", bg: "#fdf6ef" },
  pizza: { accent: "#c1653a", bg: "#fdf5ee" },
  sushi: { accent: "#2f6b63", bg: "#f6f7f2" },
  yuzu: { accent: "#7d8b2f", bg: "#faf9ec" },
  spice: { accent: "#a8672a", bg: "#fdf7ee" },
  pub: { accent: "#7a4a2e", bg: "#faf5ee" },

  plumb: { accent: "#356b74", bg: "#f5f7f6" },
  copper: { accent: "#9a6033", bg: "#fbf6f0" },
  steel: { accent: "#55636e", bg: "#f6f6f3" },

  electric: { accent: "#b8871c", bg: "#fdf9ed" },
  bolt: { accent: "#3b4f8a", bg: "#f6f6f9" },
  signal: { accent: "#6d5b8f", bg: "#f8f6fb" },
};

/** Shared shape per trade. Businesses only override what differs. */
export const CATEGORIES = {
  food: {
    label: "Restaurants & cafés",
    listId: "menu",
    nav: [
      { href: "#menu", label: "Menu" },
      { href: "#gallery", label: "The room" },
      { href: "#visit", label: "Visit" },
    ],
    ctaLabel: "Reserve a table",
    ctaHref: "#visit",
    media: "plate-1",
    shots: ["interior-1", "plate-2", "interior-3", "plate-3"],
    hours: [
      ["Tuesday — Thursday", "5.30pm — 10pm"],
      ["Friday — Saturday", "5pm — 11pm"],
      ["Sunday", "12pm — 8pm"],
      ["Monday", "Closed"],
    ],
    contactWhere: "Your suburb · dine in & takeaway",
    form: {
      title: "Book a table",
      lede: "Tell us when you'd like to come in and we'll hold a table.",
      extra: { label: "How many of you", name: "party", placeholder: "4 guests, Friday evening" },
      note: { label: "Anything we should know", name: "message", placeholder: "Allergies, a birthday, a quiet corner…" },
    },
    formNote: "A table booking form, wired to whatever inbox you prefer.",
  },

  plumbing: {
    label: "Plumbers",
    listId: "services",
    nav: [
      { href: "#services", label: "What we do" },
      { href: "#gallery", label: "Our work" },
      { href: "#visit", label: "Get a quote" },
    ],
    ctaLabel: "Call (02) 0000 0000",
    media: "van",
    shots: ["pipes", "tools", "van", "interior-1"],
    hours: [
      ["Monday — Friday", "7am — 5pm"],
      ["Saturday", "8am — 12pm"],
      ["Sunday", "Emergency only"],
      ["After hours", "24/7 call-out"],
    ],
    contactWhere: "Your suburb & surrounds · about 40km",
    form: {
      title: "Request a quote",
      lede: "Send a few details and we'll come back with a price, usually the same day.",
      extra: { label: "Suburb or address", name: "suburb", placeholder: "Your suburb, near the shops" },
      note: { label: "What needs fixing", name: "message", placeholder: "The hot water is lukewarm in the mornings, and there's a damp patch near the laundry…" },
    },
    formNote: "A quote form. Photos of the problem can be attached in the real build.",
  },

  electrical: {
    label: "Electricians",
    listId: "services",
    nav: [
      { href: "#services", label: "What we do" },
      { href: "#gallery", label: "Our work" },
      { href: "#visit", label: "Get a quote" },
    ],
    ctaLabel: "Call (02) 0000 0000",
    media: "tools",
    shots: ["board", "cable", "tools", "light"],
    hours: [
      ["Monday — Friday", "7am — 5pm"],
      ["Saturday", "8am — 12pm"],
      ["Sunday", "Emergency only"],
      ["After hours", "Call-out available"],
    ],
    contactWhere: "Your suburb & surrounds · about 40km",
    form: {
      title: "Request a quote",
      lede: "Send a few details and we'll come back with a price, usually the same day.",
      extra: { label: "Suburb or address", name: "suburb", placeholder: "Your suburb, near the school" },
      note: { label: "What needs doing", name: "message", placeholder: "Half the kitchen power points are dead and the safety switch keeps tripping…" },
    },
    formNote: "A quote form. Switchboard photos can be attached in the real build.",
  },
};

export const BUSINESSES = [
  /* ------------------------------------------------------------ food (8) */
  {
    slug: "malan-wok",
    name: "Malan Wok & Rice Chinese Food",
    short: "Malan Wok",
    category: "food",
    theme: "wok",
    kicker: "Chinese takeaway · Wok-fired to order",
    heading: ["Wok hei,", "every night."],
    lede: "Fried rice, hand-folded dumplings and noodles pulled through a screaming wok. Order ahead, pick it up hot, ten minutes from home.",
    facts: ["Open 7 nights", "Order ahead by phone", "Cash & card"],
    rating: { value: "4.7", label: "From 388 reviews" },
    media: { a: "plate-2", alt: "a bowl of noodles with chopsticks" },
    band: ["Wok-fried to order", "Hand-folded dumplings", "Family portions", "Open till late", "MSG-free on request", "Ready in 10 minutes"],
    list: {
      kicker: "The menu",
      title: "Cooked when you order it",
      lede: "The same wok dishes every night, plus whatever the chef feels like doing with the day's greens.",
      items: [
        { name: "Special fried rice", price: "16", desc: "Prawn, char siu and egg through jasmine rice." },
        { name: "Hand-folded dumplings", price: "12", desc: "Twelve to a plate, steamed then crisped in the pan.", tag: "House" },
        { name: "Singapore noodles", price: "18", desc: "Curried rice noodles with prawn and capsicum." },
        { name: "Salt & pepper squid", price: "22", desc: "Tossed with chilli, garlic and spring onion." },
        { name: "Honey prawns", price: "24", desc: "Light batter, and a glaze that stays on the prawn." },
        { name: "Combination chow mein", price: "19", desc: "Egg noodles, beef, chicken and bok choy." },
      ],
    },
    work: { kicker: "The kitchen", title: "One wok, big flame", lede: "What the food looks like before it goes in the bag." },
    shots: [
      { a: "plate-2", c: "Noodles, straight from the wok" },
      { a: "interior-3", c: "Waiting at the counter" },
      { a: "plate-3", c: "Something sweet to finish" },
      { a: "interior-2", c: "The dining room" },
    ],
    visitTitle: "Order or find us",
    area: "Your suburb",
    form: { title: "Order ahead", lede: "Send the order and a time and we'll have it bagged and waiting." },
    blurb: "A takeaway page built to be read on a phone — the menu, the hours and an order form, one tap away.",
  },
  {
    slug: "flavrhub",
    name: "FlavrHub",
    short: "FlavrHub",
    category: "food",
    theme: "cafe",
    kicker: "All-day kitchen · Breakfast from 7",
    heading: ["Good food,", "no fuss."],
    lede: "A corner kitchen doing big breakfasts, bowls and a proper flat white. Walk in, or order at the counter and take it across the road.",
    facts: ["Open 7 days", "All-day breakfast", "Kids welcome"],
    rating: { value: "4.6", label: "From 512 reviews" },
    media: { a: "plate-1", alt: "a plated breakfast" },
    band: ["All-day breakfast", "Single origin coffee", "Vegan options", "Takeaway window", "Kids menu", "Dog friendly"],
    list: {
      kicker: "The menu",
      title: "Runs all day, from open",
      lede: "Breakfast finishes when the kitchen does, which is when we close.",
      items: [
        { name: "The Hub big breakfast", price: "27", desc: "Eggs your way, bacon, halloumi, mushrooms, sourdough.", tag: "Most ordered" },
        { name: "Chilli scrambled eggs", price: "21", desc: "Soft eggs, a chilli jam that bites back, on buttered toast." },
        { name: "Halloumi & avocado bowl", price: "23", desc: "Charred halloumi, avocado, quinoa, lemon dressing." },
        { name: "Buttermilk pancakes", price: "19", desc: "Stacked, with maple and a scoop of vanilla bean." },
        { name: "Beef brisket burger", price: "24", desc: "Slow-cooked brisket, slaw, pickles, brioche." },
        { name: "Flat white", price: "5.50", desc: "Single origin, rotated monthly, always on the board." },
      ],
    },
    work: { kicker: "The room", title: "Bright, busy, easy", lede: "Come in, take the table by the window, and don't rush." },
    shots: [
      { a: "interior-1", c: "Tables by the window" },
      { a: "plate-3", c: "Coffee and something sweet" },
      { a: "interior-2", c: "The counter" },
      { a: "plate-1", c: "Off the all-day menu" },
    ],
    visitTitle: "Come in",
    area: "Your suburb",
    form: { title: "Book a table", lede: "Tables of six or more — give us a heads up and we'll set it up for you." },
    blurb: "A café page with the menu up front — breakfast, coffee and a takeaway window in the header.",
  },
  {
    slug: "yuzu-norwest",
    name: "Yuzu Norwest",
    short: "Yuzu Norwest",
    category: "food",
    theme: "yuzu",
    kicker: "Japanese kitchen · Norwest",
    heading: ["Clean flavours,", "quiet room."],
    lede: "Sashimi cut to order, a short sake list, and a warm room that stays calm even when every table is full.",
    facts: ["Sashimi cut to order", "Sake & Japanese beer", "Bookings recommended"],
    rating: { value: "4.8", label: "From 274 reviews" },
    media: { a: "plate-2", alt: "a bowl of ramen-style noodles" },
    band: ["Sashimi cut to order", "Sake list", "Omakase Fridays", "Vegan set menu", "Bookings recommended", "Group tables"],
    list: {
      kicker: "The menu",
      title: "Small dishes, then the sushi",
      lede: "Order a few things at a time. The kitchen will pace it for you if you ask.",
      items: [
        { name: "Yuzu salmon sashimi", price: "24", desc: "Six pieces, cut to order, with a yuzu-salt dip.", tag: "Signature" },
        { name: "Chicken karaage", price: "16", desc: "Marinated thigh, fried twice, with kewpie mayo." },
        { name: "Wagyu tataki", price: "29", desc: "Seared rare, ponzu, shaved daikon." },
        { name: "Agedashi tofu", price: "14", desc: "Silken tofu in a light dashi broth." },
        { name: "Salmon aburi roll", price: "21", desc: "Torched salmon, avocado, a whisper of yuzu kosho." },
        { name: "Matcha crème brûlée", price: "15", desc: "Cracked sugar, bitter matcha. Worth the ten minutes." },
      ],
    },
    work: { kicker: "The room", title: "Counter, then tables", lede: "Sit at the counter and watch the fish being cut, or take a table by the window." },
    shots: [
      { a: "interior-3", c: "The sushi counter" },
      { a: "plate-2", c: "Bowls from the kitchen" },
      { a: "interior-1", c: "The dining room" },
      { a: "plate-3", c: "Tea and dessert" },
    ],
    visitTitle: "Book a table",
    area: "Norwest & the Hills",
    form: { title: "Reserve a table", lede: "Tell us the night and how many, and we'll confirm it by text." },
    blurb: "A quiet, considered page for a Japanese kitchen — sashimi, sake and a booking form always in reach.",
  },
  {
    slug: "elena-ristorante",
    name: "elena ristorante",
    short: "elena ristorante",
    category: "food",
    theme: "bistro",
    kicker: "Italian · Made by hand",
    heading: ["Slow food,", "long table."],
    lede: "Pasta rolled every morning, a wood oven for the secondi, and a wine list that leans Italian and doesn't apologise for it.",
    facts: ["Hand-rolled pasta daily", "Wood-fired mains", "Function room upstairs"],
    rating: { value: "4.7", label: "From 431 reviews" },
    media: { a: "plate-2", alt: "a bowl of hand-rolled pasta" },
    band: ["Hand-rolled pasta", "Wood-fired mains", "Italian wine list", "Group menus", "Function room", "Sunday lunch"],
    list: {
      kicker: "The menu",
      title: "What's on tonight",
      lede: "The pasta changes with what's fresh. The classics never leave.",
      items: [
        { name: "Tagliatelle ragù", price: "32", desc: "Eight-hour beef and pork ragù, parmigiano, torn basil.", tag: "House" },
        { name: "Burrata & heirloom tomato", price: "22", desc: "Pugliese burrata, basil oil, aged balsamic." },
        { name: "Gnocchi sorrentina", price: "30", desc: "Potato gnocchi, san marzano, fior di latte." },
        { name: "Wood-fired branzino", price: "46", desc: "Whole fish, lemon, rosemary, good olive oil." },
        { name: "Veal saltimbocca", price: "42", desc: "Prosciutto, sage, white wine, spinach." },
        { name: "Tiramisù al cucchiaio", price: "16", desc: "Made in the morning, spooned at the table." },
      ],
    },
    work: { kicker: "The room", title: "Warm, and a bit loud", lede: "Tiled floors, timber tables, candles in old wine bottles." },
    shots: [
      { a: "interior-1", c: "The dining room" },
      { a: "plate-2", c: "Pasta, rolled this morning" },
      { a: "interior-3", c: "The bar" },
      { a: "plate-1", c: "From the wood oven" },
    ],
    visitTitle: "Find us",
    area: "Your suburb",
    form: { title: "Book a table", lede: "For groups and functions tell us roughly how many and we'll send the set menus." },
    blurb: "A trattoria page with the pasta up top, a warm gallery and bookings one tap away.",
  },
  {
    slug: "kn-cafe-pizza",
    name: "KN Cafe, Pizza, Restaurant",
    short: "KN Cafe & Pizza",
    category: "food",
    theme: "pizza",
    kicker: "Cafe by day · Pizza by night",
    heading: ["Coffee at seven,", "pizza at six."],
    lede: "One kitchen, two shifts. Flat whites and focaccia through the morning, wood-fired pizza from the moment the oven is hot.",
    facts: ["Wood-fired oven", "Open 7 days", "Delivery in the area"],
    rating: { value: "4.5", label: "From 596 reviews" },
    media: { a: "plate-3", alt: "coffee and dessert on a table" },
    band: ["Wood-fired pizza", "All-day breakfast", "Delivery & pick-up", "Family friendly", "BYO wine", "Late kitchen"],
    list: {
      kicker: "The menu",
      title: "Two menus, one kitchen",
      lede: "Breakfast rolls until 11, then the oven takes over for the rest of the day.",
      items: [
        { name: "Margherita", price: "20", desc: "San marzano, fior di latte, basil. Ninety seconds in the oven.", tag: "Classic" },
        { name: "Diavola", price: "25", desc: "Spicy salami, chilli honey, oregano." },
        { name: "Prosciutto & rocket", price: "28", desc: "Added after the bake, so nothing wilts." },
        { name: "Chicken parmigiana", price: "29", desc: "Crumbed breast, napoli, ham, mozzarella, chips." },
        { name: "Big breakfast", price: "25", desc: "Two eggs, bacon, sausage, hash, tomato, toast." },
        { name: "Cappuccino", price: "5", desc: "Seven days a week, from the machine at the front." },
      ],
    },
    work: { kicker: "The kitchen", title: "The oven does the work", lede: "A look at the room, the oven, and what comes out of it." },
    shots: [
      { a: "interior-2", c: "Morning shift" },
      { a: "plate-1", c: "Straight from the oven" },
      { a: "plate-3", c: "Coffee and cake" },
      { a: "interior-1", c: "The dining room" },
    ],
    visitTitle: "Eat in or take away",
    area: "Your suburb",
    form: { title: "Order for pick-up", lede: "Send the order and a time and we'll have it boxed and ready at the counter." },
    blurb: "A café-and-pizzeria page that switches from breakfast to wood-fired without changing its layout.",
  },
  {
    slug: "pista-house",
    name: "Pista house Bellavista",
    short: "Pista House",
    category: "food",
    theme: "spice",
    kicker: "Hyderabadi kitchen · Bella Vista",
    heading: ["Real spice,", "done properly."],
    lede: "Dum biryani sealed and slow-cooked, kebabs off the charcoal, and gravies built from scratch every morning.",
    facts: ["Dum biryani daily", "Charcoal kebabs", "Full vegetarian menu"],
    rating: { value: "4.7", label: "From 1,204 reviews" },
    media: { a: "plate-1", alt: "a plated curry with rice" },
    band: ["Dum biryani", "Charcoal kebabs", "Vegan & vegetarian", "Family platters", "Catering available", "Takeaway & delivery"],
    list: {
      kicker: "The menu",
      title: "From the Hyderabadi kitchen",
      lede: "Biryani is cooked in sealed pots and sells out most nights — worth ordering ahead.",
      items: [
        { name: "Hyderabadi dum biryani", price: "26", desc: "Sealed and slow-cooked with saffron, fried onion and mint.", tag: "Signature" },
        { name: "Chicken 65", price: "18", desc: "Crisp, curry-leaf tempered, with a yoghurt dip." },
        { name: "Paneer butter masala", price: "22", desc: "Cashew gravy, kasuri methi, a swirl of cream." },
        { name: "Seekh kebab", price: "20", desc: "Minced lamb, charcoal-grilled, onion and lemon." },
        { name: "Gongura mutton", price: "29", desc: "Sorrel leaves, slow-cooked until the meat gives way." },
        { name: "Double ka meetha", price: "12", desc: "Fried bread pudding, saffron milk, pistachio." },
      ],
    },
    work: { kicker: "The kitchen", title: "Slow pots, hot coals", lede: "The biryani pots, the grill, and the room they come out into." },
    shots: [
      { a: "plate-1", c: "Out of the sealed pot" },
      { a: "interior-1", c: "The dining room" },
      { a: "plate-3", c: "Something sweet" },
      { a: "interior-2", c: "Waiting for takeaway" },
    ],
    visitTitle: "Find us",
    area: "Bella Vista & surrounds",
    form: { title: "Order or book", lede: "Tell us what you need and whether it's a table or a takeaway." },
    blurb: "A busy Indian kitchen page — biryani, kebabs and a catering line, all above the fold.",
  },
  {
    slug: "sushi-culture",
    name: "Sushi Culture - Bella Vista",
    short: "Sushi Culture",
    category: "food",
    theme: "sushi",
    kicker: "Sushi train & kitchen · Bella Vista",
    heading: ["Fresh off", "the belt."],
    lede: "Plates on the belt, a hand-roll bar, and sashimi cut to order. In and out in half an hour, or settle in for the afternoon.",
    facts: ["Sushi train", "Hand rolls made to order", "Takeaway packs"],
    rating: { value: "4.6", label: "From 842 reviews" },
    media: { a: "plate-2", alt: "a bowl of noodles beside sushi plates" },
    band: ["Sushi train", "Hand-roll bar", "Sashimi platters", "Takeaway packs", "Kids plates", "Green tea on the house"],
    list: {
      kicker: "The menu",
      title: "From the belt and the bar",
      lede: "Everything on the belt is priced by plate colour. The bar takes orders.",
      items: [
        { name: "Salmon nigiri", price: "6", desc: "Two pieces, cut to order, on warm shari.", tag: "Belt favourite" },
        { name: "Spicy tuna hand roll", price: "9", desc: "Nori crisp, made as you order it." },
        { name: "Sashimi platter", price: "32", desc: "Twelve pieces, chef's choice, wasabi and pickles." },
        { name: "Chicken katsu don", price: "19", desc: "Panko crumbed, egg, onion, sweet dashi over rice." },
        { name: "Prawn tempura", price: "16", desc: "Light batter, whole prawns, tentsuyu dipping sauce." },
        { name: "Miso soup", price: "5", desc: "Dashi, tofu, wakame, spring onion." },
      ],
    },
    work: { kicker: "The belt", title: "Around it goes", lede: "The counter, the belt, and the plates worth waiting for." },
    shots: [
      { a: "interior-3", c: "Around the belt" },
      { a: "plate-2", c: "From the hot kitchen" },
      { a: "interior-1", c: "Booths and tables" },
      { a: "plate-1", c: "Plated to order" },
    ],
    visitTitle: "Come in",
    area: "Bella Vista & surrounds",
    form: { title: "Order a platter", lede: "Platters need an hour's notice — tell us the size and the pick-up time." },
    blurb: "A sushi bar page with prices by plate, a platter order form and the belt hours spelled out.",
  },
  {
    slug: "king-of-the-castle",
    name: "King Of The Castle",
    short: "King Of The Castle",
    category: "food",
    theme: "pub",
    kicker: "Local pub · Kitchen till late",
    heading: ["The local,", "done right."],
    lede: "Cold beer, a proper schnitzel, and a kitchen that stays open later than it probably should. Bring the dog, bring the kids.",
    facts: ["Kitchen till late", "Local & craft taps", "Live music Fridays"],
    rating: { value: "4.5", label: "From 967 reviews" },
    media: { a: "interior-3", alt: "a pub bar counter" },
    band: ["Craft & local taps", "Kitchen till late", "Live music Fridays", "Sunday roast", "Beer garden", "Dog friendly"],
    list: {
      kicker: "The menu",
      title: "Pub food, no shortcuts",
      lede: "Cooked to order, and served until the kitchen calls last orders at nine.",
      items: [
        { name: "Chicken schnitzel", price: "28", desc: "Pounded thin, pan-fried, with chips and slaw.", tag: "House" },
        { name: "300g rib-eye", price: "44", desc: "Grass-fed, chimichurri, roast potatoes." },
        { name: "Beef & Guinness pie", price: "27", desc: "Slow-cooked, puff lid, mash and peas." },
        { name: "Salt & pepper squid", price: "21", desc: "With lime aioli and a lot of napkins." },
        { name: "Sunday roast", price: "32", desc: "Sundays only, until it runs out." },
        { name: "Local pale ale", price: "9", desc: "Rotating taps — ask what's on." },
      ],
    },
    work: { kicker: "The pub", title: "Front bar, back garden", lede: "Timber, tiles, and a beer garden that gets busy by five." },
    shots: [
      { a: "interior-3", c: "The front bar" },
      { a: "plate-1", c: "Off the grill" },
      { a: "interior-2", c: "The dining side" },
      { a: "plate-3", c: "Pudding and a coffee" },
    ],
    visitTitle: "Find us",
    area: "Your suburb",
    form: { title: "Book a table", lede: "Groups of eight or more — we'll hold the long table out the back." },
    blurb: "A pub page for a place that lives on locals — tap list, kitchen hours and a booking form.",
  },

  /* -------------------------------------------------------- plumbing (8) */
  {
    slug: "cls-plumbing",
    listedAs: "CLS PLUMBING SOLUTIONS",
    name: "CLS Plumbing Solutions",
    short: "CLS Plumbing",
    category: "plumbing",
    theme: "trade",
    kicker: "Plumbing & gas · Licensed since 2009",
    heading: ["Turned up on time,", "fixed the first time."],
    lede: "Blocked drains, hot water and gas fitting. You get the price before the van is unpacked, not after.",
    facts: ["24/7 call-outs", "Upfront pricing", "Licensed & insured"],
    rating: { value: "4.9", label: "From 214 reviews" },
    band: ["24/7 emergency", "Upfront pricing", "Same-day service", "Gas fitting", "Hot water specialists", "Seniors discount"],
    list: {
      kicker: "What we do",
      title: "Everything domestic, nothing dodged",
      lede: "Prices below are starting points. The real figure comes before anyone starts work.",
      items: [
        { name: "Blocked drains", price: "from 149", desc: "Camera down the line first, so we fix the cause and not the symptom.", tag: "Same day" },
        { name: "Burst & leaking pipes", price: "from 189", desc: "Traced and replaced, usually inside the one visit." },
        { name: "Hot water systems", price: "from 220", desc: "Repair, replace or upgrade, with the old unit taken away." },
        { name: "Leak detection", price: "from 165", desc: "Acoustic and thermal, so we open one wall instead of five." },
        { name: "Bathroom & kitchen fit-outs", price: "quoted", desc: "Rough-in to the final tap, working around your tiler." },
        { name: "Gas fitting", price: "from 175", desc: "Cooktops, heaters and outdoor lines, certified and compliant." },
      ],
    },
    work: { kicker: "Our work", title: "Neat, and left tidy", lede: "Boots off at the door, drop sheets down, and the old parts taken with us." },
    shots: [
      { a: "pipes", c: "Repipe in a 1930s terrace" },
      { a: "tools", c: "What's in the van" },
      { a: "interior-1", c: "Bathroom fit-out" },
      { a: "van", c: "First call of the day" },
    ],
    visitTitle: "Get a quote",
    area: "Your suburb & surrounds",
    blurb: "A trades page that leads with the phone number — services, service area and a quote form.",
  },
  {
    slug: "rodman-plumbing",
    name: "Rodman Plumbing Pty Ltd",
    short: "Rodman Plumbing",
    category: "plumbing",
    theme: "plumb",
    kicker: "Plumbing & maintenance · Family run",
    heading: ["Three generations,", "same number."],
    lede: "The same family has run this van since the eighties. Repairs, renovations and the jobs other plumbers would rather not take.",
    facts: ["Family owned", "Renovations welcome", "Emergency repairs"],
    rating: { value: "4.8", label: "From 176 reviews" },
    media: { a: "pipes", alt: "copper pipework with a valve" },
    band: ["Family owned", "Renovations", "Emergency repairs", "Insurance work", "Strata & real estate", "Free quotes"],
    list: {
      kicker: "What we do",
      title: "Repairs, renovations and everything between",
      lede: "If it moves water or gas, we've probably seen it before.",
      items: [
        { name: "Emergency repairs", price: "from 180", desc: "Burst pipes and flooding, day or night." },
        { name: "Renovation rough-ins", price: "quoted", desc: "Bathrooms and kitchens, plumbed to the drawings.", tag: "Renovations" },
        { name: "Roof & gutter leaks", price: "from 195", desc: "Found, sealed and tested before we leave." },
        { name: "Taps, toilets & cisterns", price: "from 140", desc: "The small jobs, done properly and charged fairly." },
        { name: "Water pressure & filtration", price: "from 210", desc: "Whole-house filters and pressure valves." },
        { name: "Strata & real estate maintenance", price: "quoted", desc: "Scheduled and reactive work for agents." },
      ],
    },
    work: { kicker: "Our work", title: "From a leak to a whole bathroom", lede: "Old houses, tight access, and pipes nobody has touched in fifty years." },
    shots: [
      { a: "pipes", c: "Old copper, replaced" },
      { a: "tools", c: "Hand tools and fittings" },
      { a: "interior-1", c: "A finished renovation" },
      { a: "van", c: "The same van, new numberplate" },
    ],
    visitTitle: "Request a plumber",
    area: "Your suburb & surrounds",
    blurb: "A family-business page — a long history up front, clear services and an after-hours line.",
  },
  {
    slug: "core-plumbing-gas",
    name: "Core Plumbing and Gas Solutions",
    short: "Core Plumbing",
    category: "plumbing",
    theme: "copper",
    kicker: "Plumbing, gas & drainage · Commercial & domestic",
    heading: ["Diagnosed properly,", "then priced."],
    lede: "Drainage, gas and hydraulic work for homes and small commercial sites. We find the real problem before quoting the fix.",
    facts: ["Commercial & domestic", "CCTV drainage", "Compliance certificates"],
    rating: { value: "4.8", label: "From 132 reviews" },
    media: { a: "tools", alt: "spanners and a pipe wrench" },
    band: ["CCTV drain cameras", "Gas compliance", "Commercial maintenance", "Backflow testing", "Same-day quotes", "Fully insured"],
    list: {
      kicker: "What we do",
      title: "Drainage, gas and hydraulic",
      lede: "Servicing homes, cafés and small industrial sites.",
      items: [
        { name: "CCTV drain inspection", price: "from 260", desc: "Recorded, so you can see exactly what we saw.", tag: "Reported" },
        { name: "Drain cleaning & jetting", price: "from 210", desc: "High-pressure jetting, and roots cut out." },
        { name: "Gas compliance & certification", price: "quoted", desc: "Cooktops, heaters and certificates issued on the spot." },
        { name: "Backflow & TMV testing", price: "from 240", desc: "Annual testing for commercial premises." },
        { name: "Sewer & stormwater repairs", price: "quoted", desc: "Excavation, relining and making good." },
        { name: "Commercial maintenance", price: "contract", desc: "Scheduled servicing with one point of contact." },
      ],
    },
    work: { kicker: "Our work", title: "Sites, lines and certificates", lede: "Commercial jobs need the paperwork as much as the pipework." },
    shots: [
      { a: "pipes", c: "Riser and plant room work" },
      { a: "tools", c: "Jetting and camera gear" },
      { a: "van", c: "On site" },
      { a: "interior-1", c: "A completed fit-out" },
    ],
    visitTitle: "Book an inspection",
    area: "Your suburb & surrounds",
    blurb: "A plumbing-and-gas page for commercial work, with certificates and reporting front and centre.",
  },
  {
    slug: "plumbers-today",
    name: "Plumbers Today",
    short: "Plumbers Today",
    category: "plumbing",
    theme: "steel",
    kicker: "Same-day plumbing · 7 days",
    heading: ["Call now,", "fixed today."],
    lede: "A plumber on the road seven days a week, with the parts on board to finish most jobs on the first visit.",
    facts: ["7 days a week", "Same-day service", "No call-out fee before 5pm"],
    rating: { value: "4.4", label: "From 389 reviews" },
    media: { a: "van", alt: "a work van parked at a kerb" },
    band: ["Same-day service", "7 days a week", "No call-out fee", "Fixed price quotes", "Senior discounts", "Card or cash"],
    list: {
      kicker: "What we fix",
      title: "One visit, wherever possible",
      lede: "We carry the common parts, so most jobs don't need a second appointment.",
      items: [
        { name: "Taps & leaking fittings", price: "from 130", desc: "Washers, cartridges and mixers, replaced on the spot." },
        { name: "Toilets & cisterns", price: "from 145", desc: "Running, leaking or cracked — refitted or replaced." },
        { name: "Blocked drains", price: "from 160", desc: "Machined or jetted, with a camera if it keeps coming back.", tag: "Same day" },
        { name: "Hot water", price: "from 199", desc: "Elements, thermostats and full replacements." },
        { name: "Burst pipes", price: "from 185", desc: "Isolated, repaired and pressure-tested." },
        { name: "Tap & toilet installation", price: "from 150", desc: "Supply your own, or we'll grab them on the way." },
      ],
    },
    work: { kicker: "Recent jobs", title: "Quick jobs, clean finish", lede: "Most of our work is small, awkward, and done in an afternoon." },
    shots: [
      { a: "van", c: "On the road by six" },
      { a: "pipes", c: "A new tap set, fitted" },
      { a: "tools", c: "Parts we carry" },
      { a: "interior-1", c: "Under-sink, made good" },
    ],
    visitTitle: "Book a plumber",
    area: "Your suburb & surrounds",
    blurb: "A fast-read trades page where fixed-price jobs and the same-day promise are impossible to miss.",
  },
  {
    slug: "plumbers-2-you",
    name: "Plumbers 2 You",
    short: "Plumbers 2 You",
    category: "plumbing",
    theme: "trade",
    kicker: "Mobile plumbers · We come to you",
    heading: ["We come", "to you."],
    lede: "No shopfront, no waiting room. Two vans stocked for the day, working across the area from early until it's dark.",
    facts: ["Two vans on the road", "Pensioner rates", "Free on-site quotes"],
    rating: { value: "4.6", label: "From 158 reviews" },
    media: { a: "van", alt: "a service van with a roof rack" },
    band: ["Mobile service", "Pensioner rates", "Free on-site quotes", "Emergency repairs", "Hot water", "Gas fitting"],
    list: {
      kicker: "How it works",
      title: "Booked, dispatched, done",
      lede: "Tell us the suburb and the problem, and we'll give you a window — not a whole day.",
      items: [
        { name: "Booked service call", price: "from 135", desc: "A two-hour window, and a text when the van leaves.", tag: "Popular" },
        { name: "Emergency call-out", price: "from 220", desc: "Blockages, bursts, and no hot water." },
        { name: "Hot water replacement", price: "from 260", desc: "Same-day swaps where the model allows." },
        { name: "Tap & toilet repairs", price: "from 125", desc: "The list of small things, done in one visit." },
        { name: "Drain clearing", price: "from 170", desc: "Machine or jetter, depending on the line." },
        { name: "Gas appliance connection", price: "from 165", desc: "Cooktops, bayonets and outdoor heaters." },
      ],
    },
    work: { kicker: "On the road", title: "Vans, not offices", lede: "Everything we need is in the van, which is why we usually finish on the day." },
    shots: [
      { a: "van", c: "Two vans, on the road" },
      { a: "tools", c: "Stocked for the day" },
      { a: "pipes", c: "Taps and fittings" },
      { a: "interior-1", c: "A laundry, sorted" },
    ],
    visitTitle: "Book a visit",
    area: "Your suburb & surrounds",
    blurb: "A mobile-trade page where the service area and the booking window do the selling.",
  },
  {
    slug: "we-plumb",
    name: "We Plumb Plumbing Services",
    short: "We Plumb",
    category: "plumbing",
    theme: "plumb",
    kicker: "Plumbing & drainage · Residential",
    heading: ["Small jobs", "welcome."],
    lede: "The leaking tap, the running toilet, the drain that gurgles. No job too small, and no lecture about how it happened.",
    facts: ["No job too small", "Fixed price, agreed first", "Weekend bookings"],
    rating: { value: "4.7", label: "From 203 reviews" },
    media: { a: "pipes", alt: "pipework with a valve wheel" },
    band: ["No job too small", "Fixed prices", "Weekend bookings", "Drainage", "Hot water", "Taps & toilets"],
    list: {
      kicker: "What we do",
      title: "The whole list, not just the big ones",
      lede: "We'd rather do six small jobs properly than one big one in a hurry.",
      items: [
        { name: "Leaking taps & mixers", price: "from 125", desc: "Reseated or replaced, with the reason explained." },
        { name: "Running toilets", price: "from 135", desc: "Cisterns, valves and seals." },
        { name: "Blocked sinks & drains", price: "from 160", desc: "Cleared and tested before we pack up.", tag: "Same day" },
        { name: "Hot water repairs", price: "from 190", desc: "Elements, thermostats and relief valves." },
        { name: "Dishwasher & washing machine installs", price: "from 145", desc: "Including the new hose, so it doesn't leak next week." },
        { name: "Outdoor taps & irrigation", price: "from 140", desc: "Garden taps, lines and simple irrigation." },
      ],
    },
    work: { kicker: "Our work", title: "Tidy, careful, finished", lede: "Plastic down, shoes off, and the cupboard left better than we found it." },
    shots: [
      { a: "pipes", c: "A tap, re-seated" },
      { a: "tools", c: "The everyday kit" },
      { a: "interior-1", c: "Under-bench, sorted" },
      { a: "van", c: "Out on a Saturday" },
    ],
    visitTitle: "Book a time",
    area: "Your suburb & surrounds",
    blurb: "A residential page that says the small jobs are welcome — which is what most people are searching for.",
  },
  {
    slug: "rvf-plumbing",
    name: "RVF Plumbing Solutions",
    short: "RVF Plumbing",
    category: "plumbing",
    theme: "copper",
    kicker: "Plumbing & civil · Project work",
    heading: ["Planned, piped,", "signed off."],
    lede: "Fit-outs, civil drainage and maintenance plumbing for builders, developers and owners, with the paperwork to match.",
    facts: ["Builder & developer work", "Site-ready crews", "Compliance documentation"],
    rating: { value: "4.8", label: "From 96 reviews" },
    media: { a: "tools", alt: "wrenches and fittings" },
    band: ["Project plumbing", "Civil drainage", "Builder partnerships", "Compliance reporting", "Site crews", "Programmed maintenance"],
    list: {
      kicker: "Capabilities",
      title: "Where we work best",
      lede: "Contract and project work, from a single fit-out to a staged development.",
      items: [
        { name: "New build rough-in", price: "quoted", desc: "Set out to plan, inspected and signed off stage by stage.", tag: "Project" },
        { name: "Civil & stormwater drainage", price: "quoted", desc: "Excavation, pits and certified connections." },
        { name: "Fit-out plumbing", price: "quoted", desc: "Retail, hospitality and office fit-outs on program." },
        { name: "Programmed maintenance", price: "contract", desc: "Scheduled servicing for strata and asset owners." },
        { name: "Hydraulic plan review", price: "included", desc: "We read the drawings and flag the problems early." },
        { name: "Defect rectification", price: "quoted", desc: "Fixing what someone else walked away from." },
      ],
    },
    work: { kicker: "Projects", title: "Sites we're proud of", lede: "Work from the ground up, documented at every stage." },
    shots: [
      { a: "pipes", c: "Riser and stack work" },
      { a: "van", c: "Crews on site" },
      { a: "tools", c: "Tools of the trade" },
      { a: "interior-1", c: "A staged fit-out" },
    ],
    visitTitle: "Discuss a project",
    area: "Your suburb & surrounds",
    blurb: "A contractor-facing page for project work — capability, compliance and a tender-ready contact form.",
  },
  {
    slug: "tmw-plumbing",
    name: "TMW Plumbing Services",
    short: "TMW Plumbing",
    category: "plumbing",
    theme: "steel",
    kicker: "Plumbing & gas · One plumber, one standard",
    heading: ["Do it once,", "do it right."],
    lede: "A single plumber who answers his own phone. Smaller jobs, careful work, and a price agreed before anything is cut.",
    facts: ["One plumber, one standard", "Gas & plumbing licensed", "Photo updates on the day"],
    rating: { value: "4.9", label: "From 121 reviews" },
    media: { a: "van", alt: "a single work van on a driveway" },
    band: ["Licensed plumber & gasfitter", "Photo updates", "Fixed quotes", "Renovation plumbing", "Leak repairs", "No subcontractors"],
    list: {
      kicker: "What we do",
      title: "Careful work, small crew",
      lede: "You talk to the plumber doing the work — there's no call centre in between.",
      items: [
        { name: "Leak & burst repairs", price: "from 180", desc: "Found, fixed and photographed.", tag: "Popular" },
        { name: "Gas fitting & certification", price: "from 175", desc: "Compliant installs, certificates issued." },
        { name: "Bathroom renovations", price: "quoted", desc: "Strip-out to final fit-off, staged around your other trades." },
        { name: "Tap, toilet & cistern work", price: "from 140", desc: "Small repairs, done without the fuss." },
        { name: "Kitchen plumbing", price: "quoted", desc: "Sinks, dishwashers and gas cooktops." },
        { name: "Water filter installation", price: "from 220", desc: "Under-sink and whole-house filtration." },
      ],
    },
    work: { kicker: "Recent work", title: "Finished, and photographed", lede: "Every job is photographed, so you know exactly what was done and where." },
    shots: [
      { a: "van", c: "The whole business, in one van" },
      { a: "pipes", c: "New work, old house" },
      { a: "tools", c: "Kept sharp" },
      { a: "interior-1", c: "A bathroom, finished" },
    ],
    visitTitle: "Get a quote",
    area: "Your suburb & surrounds",
    blurb: "A one-plumber page that leans on trust — licensed, photographed, and no subcontractors.",
  },

  /* ------------------------------------------------------ electrical (9) */
  {
    slug: "warran-electrical",
    name: "Warran Electrical",
    short: "Warran Electrical",
    category: "electrical",
    theme: "electric",
    kicker: "Domestic electrician · Licensed & insured",
    heading: ["Wired safely,", "priced fairly."],
    lede: "Power points, lighting, switchboards and fault finding. Same-day for anything that smells hot.",
    facts: ["Licensed & insured", "Same-day faults", "Switchboard upgrades"],
    rating: { value: "4.8", label: "From 187 reviews" },
    band: ["Same-day faults", "Switchboard upgrades", "LED lighting", "Safety switches", "Smoke alarms", "Free quotes"],
    list: {
      kicker: "What we do",
      title: "The everyday jobs, plus the ones that matter",
      lede: "Old wiring is the thing we see most, and the thing worth fixing first.",
      items: [
        { name: "Switchboard upgrades", price: "from 1450", desc: "Safety switches, surge protection and clear labelling.", tag: "Recommended" },
        { name: "Fault finding", price: "from 180", desc: "Tripping circuits and dead power points, traced properly." },
        { name: "Power points & circuits", price: "from 145", desc: "New outlets, extra circuits, outbuildings." },
        { name: "LED lighting", price: "from 165", desc: "Downlights, pendants and outdoor lighting." },
        { name: "Safety switches & smoke alarms", price: "from 220", desc: "Tested, replaced and compliant." },
        { name: "Oven & cooktop installation", price: "from 190", desc: "Hardwired appliances, connected and tested." },
      ],
    },
    work: { kicker: "Our work", title: "Boards, cable and light", lede: "Neat cable runs, and switchboards you can actually read." },
    shots: [
      { a: "board", c: "A board, upgraded" },
      { a: "light", c: "Pendants and downlights" },
      { a: "cable", c: "Cable runs, tidied" },
      { a: "tools", c: "Tested before we leave" },
    ],
    visitTitle: "Book an electrician",
    area: "Your suburb & surrounds",
    blurb: "An electrician page led by safety — switchboards, fault finding and certification.",
  },
  {
    slug: "paul-singh-electrical",
    name: "Paul Singh Electrical",
    short: "Paul Singh Electrical",
    category: "electrical",
    theme: "bolt",
    kicker: "Electrical & air conditioning · Domestic",
    heading: ["Getting it right,", "every time."],
    lede: "Lighting, power, air conditioning and the fiddly jobs in old houses. Twenty years on the tools, one van, no drama.",
    facts: ["20 years on the tools", "Air conditioning installs", "Pensioner discount"],
    rating: { value: "4.9", label: "From 143 reviews" },
    band: ["Air conditioning", "LED lighting", "Ceiling fans", "Power points", "Fault finding", "Pensioner discount"],
    list: {
      kicker: "What we do",
      title: "Lighting, power and cooling",
      lede: "Split systems installed and serviced, with the certificate sorted.",
      items: [
        { name: "Split system installation", price: "from 650", desc: "Back-to-back installs, plus the electrical work.", tag: "Popular" },
        { name: "Ceiling fans & lighting", price: "from 150", desc: "Installed, balanced and tested." },
        { name: "Extra power points", price: "from 140", desc: "New outlets where the house actually needs them." },
        { name: "Switchboard & safety switch work", price: "from 380", desc: "Upgrades and compliance repairs." },
        { name: "Fault finding", price: "from 175", desc: "Working out why the circuit keeps tripping." },
        { name: "Air conditioning service", price: "from 220", desc: "Filters, gas, and a look at the drain." },
      ],
    },
    work: { kicker: "Our work", title: "Clean installs", lede: "Straight cable, tidy brackets, and everything tested before we leave." },
    shots: [
      { a: "light", c: "Lighting, installed" },
      { a: "board", c: "A board, brought up to date" },
      { a: "tools", c: "Test gear" },
      { a: "interior-1", c: "A room, cooled" },
    ],
    visitTitle: "Get a quote",
    area: "Your suburb & surrounds",
    blurb: "An electrical page with air conditioning as a headline service — good for a warm part of the country.",
  },
  {
    slug: "pulse-mobile-auto-electrics",
    name: "Pulse Mobile Auto Electrics",
    short: "Pulse Mobile",
    category: "electrical",
    theme: "bolt",
    kicker: "Auto electrician · Mobile service",
    heading: ["We come to", "the car."],
    lede: "Batteries, alternators, wiring and electrical faults, done in your driveway or at your work. No tow truck required.",
    facts: ["Mobile — we come to you", "Batteries & alternators", "Fleet & private"],
    rating: { value: "4.7", label: "From 268 reviews" },
    media: { a: "van", alt: "a mobile service van" },
    band: ["Mobile auto electrics", "Battery replacement", "Alternator repair", "Fleet servicing", "Diagnostics", "Seven days"],
    list: {
      kicker: "What we do",
      title: "Electrical faults, fixed on site",
      lede: "Most jobs are finished in the driveway, without the car going anywhere.",
      items: [
        { name: "Battery testing & replacement", price: "from 220", desc: "Tested under load, replaced if it fails.", tag: "Same day" },
        { name: "Alternator & starter motors", price: "from 380", desc: "Removed, replaced or sent for rebuild." },
        { name: "Electrical diagnostics", price: "from 150", desc: "Parasitic drains, warning lights and no-starts." },
        { name: "Wiring & accessory installs", price: "from 180", desc: "Driving lights, UHF, dual batteries and trailer wiring." },
        { name: "Fleet servicing", price: "quoted", desc: "On-site scheduled work for small fleets." },
        { name: "Trailer & caravan wiring", price: "from 160", desc: "Lights, brakes and charging circuits." },
      ],
    },
    work: { kicker: "On the road", title: "Driveway jobs", lede: "Everything needed in the van, including the tools to read the car's own computer." },
    shots: [
      { a: "van", c: "The mobile workshop" },
      { a: "cable", c: "Wiring, replaced" },
      { a: "tools", c: "Diagnostic gear" },
      { a: "board", c: "Circuit testing" },
    ],
    visitTitle: "Book a call-out",
    area: "Your suburb & surrounds",
    blurb: "A fully mobile trade page — the service area replaces the address, and bookings go straight to the phone.",
  },
  {
    slug: "onetek-electrical",
    name: "Onetek Electrical Services",
    short: "Onetek Electrical",
    category: "electrical",
    theme: "steel",
    kicker: "Electrical · Homes & small business",
    heading: ["Fit for purpose,", "fully tested."],
    lede: "Wiring, testing and compliance for homes, offices and shops — including the test-and-tag paperwork that keeps inspections quiet.",
    facts: ["Test & tag", "Small business work", "Compliance testing"],
    rating: { value: "4.6", label: "From 118 reviews" },
    band: ["Test & tag", "Compliance testing", "Office fit-outs", "Data & comms", "Emergency lighting", "Preventive maintenance"],
    list: {
      kicker: "What we do",
      title: "Domestic, retail and office",
      lede: "The jobs that need a certificate at the end are the ones we like most.",
      items: [
        { name: "Test & tag", price: "from 5 per item", desc: "Minimum call-out applies. Tags and register supplied.", tag: "Compliance" },
        { name: "Electrical testing & reports", price: "quoted", desc: "Defect reports suitable for insurers and landlords." },
        { name: "Office & retail fit-outs", price: "quoted", desc: "Lighting, power, data and exit signage." },
        { name: "Data & communications cabling", price: "from 190", desc: "Certified data runs and patch panels." },
        { name: "Emergency & exit lighting", price: "quoted", desc: "Installed, tested and logged." },
        { name: "Preventive maintenance", price: "contract", desc: "Scheduled inspection for small sites." },
      ],
    },
    work: { kicker: "Our work", title: "Documented and compliant", lede: "Testing, tagging and reports that stand up to an inspection." },
    shots: [
      { a: "cable", c: "Data runs, certified" },
      { a: "board", c: "A board, labelled" },
      { a: "light", c: "Emergency lighting" },
      { a: "tools", c: "Test and tag kit" },
    ],
    visitTitle: "Request a service",
    area: "Your suburb & surrounds",
    blurb: "A commercial-leaning electrical page where compliance, testing and reporting are the product.",
  },
  {
    slug: "24-7-electrician-baulkham-hills",
    name: "24/7 Electrician Baulkham Hills",
    short: "24/7 Electrician",
    category: "electrical",
    theme: "electric",
    kicker: "Emergency electrician · Baulkham Hills",
    heading: ["Power out?", "We're up."],
    lede: "Day, night or the long weekend. Faults, tripping circuits and dead power, answered by a licensed electrician — not a switchboard.",
    facts: ["Answered 24 hours", "Same-hour response", "Licensed & insured"],
    rating: { value: "4.5", label: "From 311 reviews" },
    band: ["24/7 emergency", "Same-hour response", "Tripping circuits", "Switchboard repairs", "Storm damage", "No hidden fees"],
    list: {
      kicker: "Emergency work",
      title: "What we get called for at 2am",
      lede: "Call-out rates are quoted on the phone, before anyone gets in the van.",
      items: [
        { name: "Total power failure", price: "from 220", desc: "Main switch, supply fault, or the board itself.", tag: "24/7" },
        { name: "Tripping safety switches", price: "from 190", desc: "Isolated, tested and fixed on the same visit." },
        { name: "Burning smells & hot outlets", price: "from 220", desc: "Made safe immediately, repaired in daylight." },
        { name: "Storm & water damage", price: "quoted", desc: "Mains and board work after a leak." },
        { name: "Switchboard repairs", price: "from 240", desc: "Fuses, breakers and burnt-out cabling." },
        { name: "Temporary supply", price: "quoted", desc: "Something safe to run on until the real fix." },
      ],
    },
    work: { kicker: "Call-outs", title: "Through the night", lede: "Most nights we're done before the kettle has gone cold." },
    shots: [
      { a: "board", c: "A board, at midnight" },
      { a: "tools", c: "The night kit" },
      { a: "cable", c: "Supply faults, traced" },
      { a: "light", c: "Power back on" },
    ],
    visitTitle: "Call us now",
    area: "Baulkham Hills & nearby",
    form: { title: "Request a call back", lede: "If it's urgent, call — the phone is answered all night. Otherwise leave a number and we'll ring you." },
    blurb: "An emergency-first page built for someone searching at midnight — the phone number is the whole design.",
  },
  {
    slug: "hillz-electronics-security",
    name: "Hillz Electronics and Security",
    short: "Hillz Electronics",
    category: "electrical",
    theme: "signal",
    kicker: "Security & electronics · The Hills",
    heading: ["Watched over,", "not wired up wrong."],
    lede: "Alarms, cameras and intercoms installed and monitored, plus the data cabling that keeps them all talking to each other.",
    facts: ["Licensed security installer", "Cameras & alarms", "Monitoring available"],
    rating: { value: "4.8", label: "From 124 reviews" },
    media: { a: "camera", alt: "a security camera on a wall" },
    band: ["CCTV & alarms", "Intercoms", "Data cabling", "Monitoring", "Access control", "Free site visit"],
    list: {
      kicker: "What we do",
      title: "Security, sorted end to end",
      lede: "One installer for the cameras, the alarm, the intercom, and the cable feeding all of them.",
      items: [
        { name: "CCTV systems", price: "from 1200", desc: "Four cameras, recorder, phone access and cabling.", tag: "Popular" },
        { name: "Alarm systems", price: "from 950", desc: "Wired or wireless, with monitoring optional." },
        { name: "Intercoms & video entry", price: "from 850", desc: "Audio or video, with app unlock." },
        { name: "Access control", price: "quoted", desc: "Fobs, keypads and door strikes." },
        { name: "Data & network cabling", price: "from 190", desc: "Cat6 runs, patch panels and Wi-Fi coverage fixes." },
        { name: "Monitoring plans", price: "from 35/month", desc: "Back-to-base alarms and camera retention." },
      ],
    },
    work: { kicker: "Site work", title: "Cable, camera, coverage", lede: "Planned so there are no blind spots, and no cable where you can see it." },
    shots: [
      { a: "camera", c: "A camera, mounted high" },
      { a: "cable", c: "Cat6, run neatly" },
      { a: "board", c: "The recorder and patch panel" },
      { a: "tools", c: "Terminations and test gear" },
    ],
    visitTitle: "Book a site visit",
    area: "The Hills district",
    form: { title: "Book a site visit", lede: "Tell us the property and what you'd like covered, and we'll come and look." },
    blurb: "A security installer page where packages, monitoring and a free site visit are all spelled out.",
  },
  {
    slug: "watts-new-electrical",
    name: "Watts New Electrical",
    short: "Watts New",
    category: "electrical",
    theme: "electric",
    kicker: "Electrical & solar · Domestic",
    heading: ["Same house,", "smaller bill."],
    lede: "Lighting, appliances and solar-ready switchboard work, aimed at getting the power bill down without rewiring the whole place.",
    facts: ["Solar-ready upgrades", "Energy-saving lighting", "Free quotes"],
    rating: { value: "4.7", label: "From 209 reviews" },
    media: { a: "light", alt: "a pendant light over a table" },
    band: ["LED lighting", "Solar-ready boards", "Energy audits", "Hot water timers", "Power monitoring", "Free quotes"],
    list: {
      kicker: "What we do",
      title: "Lower bills, done properly",
      lede: "We start with what's actually drawing the power, then fix that.",
      items: [
        { name: "LED lighting upgrade", price: "from 260", desc: "Downlights and sensors, priced by the room.", tag: "Saves power" },
        { name: "Solar-ready switchboard", price: "from 1650", desc: "Board, protection and a clean feed ready for solar." },
        { name: "Energy audit", price: "from 180", desc: "Meter readings, appliance checks, and a written list." },
        { name: "Hot water timers & controls", price: "from 240", desc: "Stop heating water that nobody is using." },
        { name: "Power point additions", price: "from 145", desc: "Including outdoor and shed circuits." },
        { name: "Appliance installation", price: "from 165", desc: "Ovens, cooktops and rangehoods." },
      ],
    },
    work: { kicker: "Our work", title: "Measured, then upgraded", lede: "Boards, lighting and metering — before and after." },
    shots: [
      { a: "light", c: "LED, throughout" },
      { a: "board", c: "Solar-ready board" },
      { a: "cable", c: "Circuits, separated" },
      { a: "tools", c: "Metering and test gear" },
    ],
    visitTitle: "Get a quote",
    area: "Your suburb & surrounds",
    blurb: "An electrical page that sells saving money — lighting, metering and solar-ready boards.",
  },
  {
    slug: "jvr-auto-electrics",
    listedAs: "J. V R Auto Electrician & Air Conditioning Services - Asmarian John",
    name: "J.V.R Auto Electrician & Air Conditioning",
    short: "J.V.R Auto",
    category: "electrical",
    theme: "steel",
    kicker: "Auto electrics & air conditioning",
    heading: ["Auto electrics,", "done in a day."],
    lede: "Air conditioning, auto electrical faults and accessory installs for cars, utes and vans — in the workshop, or a mobile call-out.",
    facts: ["Air conditioning regas", "Auto electrical repairs", "Mobile call-outs"],
    rating: { value: "4.6", label: "From 154 reviews" },
    media: { a: "van", alt: "a workshop van with roof rack" },
    band: ["Air conditioning", "Auto electrics", "Log book servicing", "Mobile call-outs", "Fleet & trade", "Same-week bookings"],
    list: {
      kicker: "What we do",
      title: "From a regas to a full rewire",
      lede: "Diagnostics first, then a price — no guessing with your car.",
      items: [
        { name: "Air conditioning regas & service", price: "from 180", desc: "Leak tested, evacuated, recharged.", tag: "Book ahead" },
        { name: "Compressor & component replacement", price: "from 520", desc: "With the parts sourced the same week." },
        { name: "Auto electrical diagnostics", price: "from 130", desc: "Batteries, charging and starting faults." },
        { name: "Alternator & starter replacement", price: "from 340", desc: "New or rebuilt, fitted and tested." },
        { name: "Accessory installation", price: "from 160", desc: "Dual batteries, driving lights, UHF and brake controllers." },
        { name: "Pre-purchase electrical check", price: "from 120", desc: "What you'd want to know before buying it." },
      ],
    },
    work: { kicker: "In the workshop", title: "Cars, utes and vans", lede: "A look at the kind of work that comes through the door." },
    shots: [
      { a: "van", c: "Utes and vans, in for the day" },
      { a: "cable", c: "Wiring, replaced" },
      { a: "tools", c: "Diagnostics" },
      { a: "board", c: "Circuit testing" },
    ],
    visitTitle: "Book your car in",
    area: "Your suburb & surrounds",
    form: { title: "Book your car in", lede: "Tell us the car and the symptoms, and we'll book a slot." },
    blurb: "An auto-electrical and air-conditioning page — diagnostics, regas and accessory work, booked in one form.",
  },
  {
    slug: "hills-electrical-express",
    name: "Hills Electrical Express",
    short: "Hills Electrical",
    category: "electrical",
    theme: "electric",
    kicker: "Electrical · Fast turnarounds",
    heading: ["Quick to quote,", "quick to arrive."],
    lede: "Power, lighting and repairs for homes and rentals. Short jobs done the same day, with tenants and agents kept in the loop.",
    facts: ["Rental & property work", "Same-day repairs", "Photos and invoices sent"],
    rating: { value: "4.6", label: "From 233 reviews" },
    band: ["Same-day repairs", "Rental property work", "Lighting & power", "Fault finding", "Agent invoicing", "Emergency call-outs"],
    list: {
      kicker: "What we do",
      title: "Fast, tidy, documented",
      lede: "Photo of the job, invoice to the agent, and nobody chasing anyone for either.",
      items: [
        { name: "Rental repairs & maintenance", price: "from 150", desc: "Reported, photographed and invoiced to the agent.", tag: "Agents" },
        { name: "Fault finding", price: "from 170", desc: "Tripping circuits, dead power points and hot switches." },
        { name: "Light fittings & downlights", price: "from 140", desc: "Replaced or installed, up to two metres." },
        { name: "Power point installation", price: "from 145", desc: "New points, including outdoor and garage." },
        { name: "Smoke alarm replacement", price: "from 120", desc: "Interconnected alarms, to current standards." },
        { name: "Emergency call-outs", price: "from 210", desc: "Same-day where the schedule allows." },
      ],
    },
    work: { kicker: "Our work", title: "Quick jobs, tidy finish", lede: "Small electrical work, photographed before and after." },
    shots: [
      { a: "light", c: "A fitting, replaced" },
      { a: "tools", c: "Tested and tagged" },
      { a: "cable", c: "New circuits" },
      { a: "board", c: "Safety switches, checked" },
    ],
    visitTitle: "Book a job",
    area: "Your suburb & surrounds",
    form: { title: "Book a job", lede: "Property managers: send the work order and we'll schedule it and invoice straight back." },
    blurb: "A page built for property managers — same-day repairs, photos, and invoicing that needs no chasing.",
  },
];

/** Phone and email are the same obvious placeholder on every demo. */
export const PLACEHOLDER = {
  phone: "(02) 0000 0000",
  phoneHref: "tel:+61200000000",
  email: "hello@example.com",
};
